name: Terraform CI/CD Workflows

on:
  workflow_call:
    inputs:
      aws-region:
        description: "AWS Region"
        required: true
        type: string
      branch_name:
        description: "Branch Name to execute workflow"
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  terraform:
    name: Terraform CI/CD
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code (Fixed Incorrect Reference)
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch_name }}

      # Step 2: Set Up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      # Step 3: Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws-region }}

      # Step 4: Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Step 5: Validate Terraform Configuration
      - name: Terraform Validate
        run: terraform validate

      # Step 6: Check Terraform Formatting
      - name: Terraform Format
        run: terraform fmt -check

      # Step 7: Terraform Plan
      - name: Terraform Plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ inputs.aws-region }}
        run: terraform plan

      # Step 8: Terraform Apply (Fixed Branch Condition)
      - name: Terraform Apply
        if: ${{ github.ref == format('refs/heads/{0}', inputs.branch_name) }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ inputs.aws-region }}
        run: terraform apply -auto-approve
